builds:
  - name: "hpc-build"
    type: "hpc-module"
    enabled: true
    config:
      config_path: .github/ci-hpc-config.yml
      platforms:
        - gnu-12.2.0
        - gnu-8.5.0
        - nvidia-22.11
        - intel-2021.4.0
