cmake_options: -DENABLE_ALL_TESTS=ON -DBOOST_ROOT=${BOOST_ROOT_DIR} -DBOOST_INCLUDEDIR=${BOOST_INCLUDE_DIR} -DBOOST_LIBRARYDIR=${BOOST_LIB_DIR} -DOPENSSL_ROOT_DIR=${OPENSSL_ROOT_DIR} -DENABLE_STATIC_BOOST_LIBS=OFF
ctest_options: 
  - -L
  - nightly
  - -E
  - s_test|s_zombies
dependencies: |
  ecmwf/ecbuild
dependency_branch: develop
parallelism_factor: 8
