name: Dummy CD

on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
      - 'v?[0-9]+.[0-9]+.[0-9]+-*'
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    if: |
      startsWith(github.ref, 'refs/tags/') ||
      (github.event.pull_request.base.ref == github.event.repository.default_branch && github.event.label.name == 'approved-for-cd')
    uses: ecmwf/reusable-workflows/.github/workflows/main-cd.yml@cd-hpc
    with:
      ref_name: ${{ github.ref_name }}
    secrets: inherit
